using System.IO;
using System.Text;
using Robust.Shared.Utility;

namespace Content.Shared.Chemistry.Reagent;

public static class ReagentGasGenerator
{
    private static readonly string FilePath = "_Generated/reagentGases.yml";

    public static void Run(string prototypeDir)
    {
        string outputPath = Path.Combine(prototypeDir, FilePath);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, BuildYaml(prototypeDir));
    }

    private static string BuildYaml(string prototypeDir)
    {
        StringBuilder stringBuilder = new();
        stringBuilder.AppendLine(
            "# This file is automatically generated by ReagentGasGenerator. Do not edit manually.");

        foreach (var path in Directory.EnumerateFiles(prototypeDir, "*.yml", SearchOption.AllDirectories))
        {
            if (path.Contains("_Generated"))
                continue;

            string text;
            try
            {
                text = File.ReadAllText(path);
            }
            catch
            {
                continue;
            }

            string? currentId = null;
            string currentColor = "\"#FFFFFF\"";
            bool inReagentBlock = false;

            foreach (var rawLine in text.Split('\n'))
            {
                var line = rawLine.Trim();
                if (line.StartsWith("- type:"))
                {
                    if (inReagentBlock && currentId != null)
                        AppendEntry(stringBuilder, currentId, currentColor);

                    currentId = null;
                    currentColor = "\"#FFFFFF\"";
                    inReagentBlock = line.Contains("reagent");
                }
                else if (inReagentBlock)
                {
                    if (line.StartsWith("id:"))
                        currentId = line.Replace("id:", "").Trim();
                    else if (line.StartsWith("color:"))
                        currentColor = line.Replace("color:", "").Trim();
                }
            }

            if (inReagentBlock && currentId != null)
                AppendEntry(stringBuilder, currentId, currentColor);
        }
        return stringBuilder.ToString();
    }

    private static void AppendEntry(StringBuilder stringBuilder, string id, string color)
    {
        stringBuilder.AppendLine("- type: gas");
        stringBuilder.AppendLine($"  id: ReagentGas{id}");
        stringBuilder.AppendLine($"  name: {id} (gas)");
        stringBuilder.AppendLine($"  abbreviation: {id[..Math.Min(3, id.Length)]}");
        stringBuilder.AppendLine($"  color: {color}");
        stringBuilder.AppendLine("  molarMass: 0.2");
        stringBuilder.AppendLine("  specificHeat: 20");
        stringBuilder.AppendLine("");
    }

    public static string FindResourcesDir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir, "Resources")))
                return Path.Combine(dir, "Resources");
            dir = Path.GetDirectoryName(dir);
        }
        throw new Exception("[ReagentGasGenerator] Could not find Resources directory!");
    }
}

